### ISSUE TITLE
getting a not authorized error?

### ISSUE THREAD

**Issue by thepixelmonk** [rummelonp/tumblife-for-ruby#2]
```
Tumblife.configure do |config|
   config.consumer_key = TUMBLR_KEY
   config.consumer_secret = TUMBLR_SECRET
   config.oauth_token = params['oauth_token']
   config.oauth_token_secret = params['oauth_token_secret']
end

Tumblife.client.dashboard
=> APIError: Not Authorized
```

any ideas?

**Comment by rummelonp** [comment]
Maybe oauth or consumer token is wrong.
See this sample to authentication.
https://gist.github.com/1084360

**Comment by thepixelmonk** [comment]
Following the code you linked:

```
con = OAuth::Consumer.new(TUMBLR_KEY, TUMBLR_SECRET, {site: 'http://www.tumblr.com'})
r = con.get_request_token
a = r.get_access_token(oauth_token: params[:oauth_token], oauth_verifier: params[:oauth_verifier])
==> OAuth::Unauthorized: 400 Bad Request
```

**Comment by rummelonp** [comment]
Does that parameter contain what?
You must press allow button on tumblr oauth page.
And you must use a parameter that is returned by callback to your server.
![](http://29.media.tumblr.com/tumblr_l5gnydYSUu1qz8q0ho1_500.png)

**Comment by thepixelmonk** [comment]
yeah I know, I was using the 'pry' gem to enter into a console during the request, both the params variables are fetched after hitting the allow button.

**Comment by thepixelmonk** [comment]
I'll just close this since I guess it's not reproducible and something on my end.

**Comment by BananaNeil** [comment]
-_- i'm getting the same problem
