### ISSUE TITLE
undefined method configure for Tumblife:Class

### ISSUE THREAD

**Issue by mikeni** [rummelonp/tumblife-for-ruby#5]
does not work with rails 3.2.2

**Comment by rummelonp** [comment]
paste the url for that rails project repository

**Comment by thoughtpunch** [comment]
I'm getting the exact same thing. Calling the configuration as shown in the doc

I even directly called your repo as the source in the Gemfile and reinstalled the gem. Same error.

**Comment by thoughtpunch** [comment]
@mikeni Did you solve this issue for yourself?
