### ISSUE TITLE
Can't get blog...

### ISSUE THREAD

**Issue by javiersuazo** [rummelonp/tumblife-for-ruby#7]
Hi, I'm getting this:

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <link rel="icon" href="http://assets.tumblr.com/images/favicon.gif?2" type="image/gif"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta http-equiv="x-dns-prefetch-control" content="off"/>
        <meta name="robots" content="noindex"/>
        <link rel="stylesheet" href="http://assets.tumblr.com/stylesheets/compressed/status_blue.css"
        type="text/css" media="screen" charset="utf-8">
        <title>Not found</title>
    </head>
    <body onload="if (top != self) document.write('<body style=\'background:transparent;\'></body>');">
        <table height="100%" width="100%">
            <tr>
                <td align="center" valign="middle">
                    <div id="container">
                        <h1 id="l10n_title">Not found</h1>

```
                    <div class="sorry">
                        <p id="l10n_sorry_1">We couldn't find the page you were looking for.</p>
                        <p id="l10n_sorry_2">
                            Feel free to contact support if there's anything<br/>
                            we can help you find.
                        </p>
                        <p id="l10n_email_button"><a class="button" href="mailto:support@tumblr.com">Email Support</a></p>
                    </div>
                </div>
            </td>
        </tr>
    </table>
    <script type="text/javascript" language="javascript">var status_code = '404'</script>
    <script type="text/javascript" language="javascript" src="http://assets.tumblr.com/languages/errors.js"></script>
</body>
```

</html>'

**Comment by rummelonp** [comment]
paste the code to reproduce

**Comment by javiersuazo** [comment]
ok i do this:

Tumblife.configure do |config|
config.consumer_key = "the key"
config.consumer_secret = "the secret"
config.oauth_token = CompanyProfile.first.tumblr_token
config.oauth_token_secret = CompanyProfile.first.tumblr_secret_token
end

then 

client = Tumblife.client
avatar = client.avatar('myblog.tumblr.com')

and in that line i get this error

<div class="sorry">
                        <p id="l10n_sorry_1">We couldn't find the page you were looking for.</p>
                        <p id="l10n_sorry_2">
                            Feel free to contact support if there's anything<br/>
                            we can help you find.
                        </p>
                        <p id="l10n_email_button"><a class="button" href="mailto:support@tumblr.com">Email Support</a></p>
                    </div>


this is my Gemfile:

source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Bundle edge Rails instead:

# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'devise'
gem 'heroku'
gem "tumblife"
gem 'uuid'
gem 'ruby-hmac'
gem 'sqlite3'
gem 'execjs'
gem 'rest-graph'
gem 'therubyracer'
gem 'json'
gem 'databasedotcom', :git=>'https://github.com/JackSullivan/databasedotcom'
gem "bcrypt-ruby", "~> 3.0.0"
gem 'databasedotcom-rails'
gem "pg", "~> 0.11.0"
gem 'json'
gem "thin"
gem "fb_graph"
gem 'omniauth'
gem 'omniauth-facebook'
gem 'youtube_it', "~> 2.1.4"
gem 'omniauth-twitter'
gem 'twitter'
gem 'omniauth-oauth'
gem 'oauth'
gem 'tumblr-ruby'
gem 'metaforce'
#gem "paperclip", "~> 3.0"
gem "rufus-scheduler"
gem 'omniauth-tumblr'
gem 'omniauth-tumblr2', "~> 0.0.3"
gem 'attr_encrypted'
gem 'spectator-attr_encrypted'
gem 'paper_trail', '~> 2'
gem 'google_visualr', '>= 2.1'

**Comment by javiersuazo** [comment]
any idea?!

**Comment by rummelonp** [comment]
What's your environment, os, ruby version, tumblife version?

Maybe, blog URL of the argument is wrong. (eg. deleted blog, include http scheme)

![irb](http://pic.mitukiii.jp/b2046491.png)

**Comment by javiersuazo** [comment]
Hi i'm using Ubuntu 12.04, Rails 3.1.3, Tumblife 1.0.1

**Comment by javiersuazo** [comment]
I fixed it!
